"""Reproducibility-record macros: findings on the Träff et al. codes, generated from the companion project's sealed evidence.

    python3 analysis/repro_numbers.py [--companion evidence/companion]   -> paper/combined/repro_numbers.tex

Every value is read from the companion result files cited in paper/combined/reproducibility_record.md; none is
typed by hand.
"""
import argparse
import json
from pathlib import Path

V = Path(__file__).resolve().parents[1]


def load(p):
    return json.loads(Path(p).read_text())


def sci(x):
    m, e = f"{x:.2e}".split("e")
    return f"{m}\\times10^{{{int(e)}}}"


def main():
    a = argparse.ArgumentParser()
    a.add_argument("--companion", type=Path, default=V / "evidence/companion")
    r = a.parse_args().companion / "results/rescope"
    m = {}
    # A1: OpenMP composite 10x10x10 midpoint fine matrix vs exact Gauss Q1 (level 0 only)
    omp = [c for c in load(r / "hex-modal-priorart-20260923/cpu-02/results.json")["openmp_cases"] if c["level"] == 0]
    errs = [100 * c["source_sum_vs_exact_gauss"]["relative_frobenius"] for c in omp]
    m["WAMidpointMin"], m["WAMidpointMax"] = f"{min(errs):.3f}", f"{max(errs):.3f}"
    # A3: boundary contract (published host, unadapted)
    host = load(r / "hex-modal-mg-host-20260923/run-01/result.json")["states"]
    m["WAStateErrorPct"] = f"{100 * max(s['state_relative_error'] for s in host):.2f}"
    m["WASourceFixedMax"] = sci(max(s["fixed_solution_maximum"] for s in host if s["path"] == "source"))
    m["WAHostStates"] = str(len(host))
    m["WAHostStatesPassed"] = str(sum(s["passed"] for s in host))
    adapted = load(r / "hex-modal-mg-host-v2-20260923/run-01/result.json")["states"]
    m["WAAdaptedStatesPassed"] = str(sum(s["passed"] for s in adapted))
    # A4: transfer boundary/symmetry audit
    v = load(r / "hex-modal-mg-bc-audit-20260923/run-01/verification.json")
    raw = [p for p in v["pairs"] if p["variant"] == 0]
    proj = [p for p in v["pairs"] if p["variant"] == 1]
    m["WATransferPairs"] = str(len(raw))
    m["WATransferRawPassed"] = str(sum(p["passed"] for p in raw))
    m["WATransferProjPassed"] = str(sum(p["passed"] for p in proj))
    m["WATransferRawDefect"] = sci(max(abs(p["scaled_bilinear_symmetry"]) for p in raw))
    m["WATransferRawFixed"] = f"{max(p['fixed_output_maximum'] for p in raw):.1f}"
    m["WATransferProjDefect"] = sci(max(abs(p["scaled_bilinear_symmetry"]) for p in proj))
    # A6: damping replay (certified conservative weights vs original omega 0.6)
    rep = load(r / "hex-modal-mg-damping-gpu-20260923/rental-01/local-verification.json")["replays"]
    for name, key in (("certified", "WADampingCertified"), ("original", "WADampingOriginal")):
        rows = [x for x in rep if x["damping"] == name]
        m[key] = f"{sum(bool(x['passed']) for x in rows)}/{len(rows)}"
    out = V / "paper/combined/repro_numbers.tex"
    out.write_text("% generated by analysis/repro_numbers.py -- do not edit\n" +
                   "".join(f"\\newcommand{{\\{k}}}{{{val}}}\n" for k, val in sorted(m.items())))
    print(out.read_text())


if __name__ == "__main__":
    main()
