"""Tables for the paper from Voxel session A's independent local verification. No hand-typed numbers.

    python3 analysis/session_a_tables.py results/session-a-20260923
Writes paper/<tag>_tables.md and paper/<tag>_numbers.json; tag defaults to session_a.
"""
import json
import statistics
import sys
from pathlib import Path

V = Path(__file__).resolve().parents[1]


def main():
    run = Path(sys.argv[1]).resolve()
    tag = sys.argv[2] if len(sys.argv) > 2 else 'session_a'
    ver = json.loads((run / 'local-verification.json').read_text())
    res = json.loads((run / 'remote/run-01/result.json').read_text())
    d = ver['decision']
    L = [f'# {tag} tables (generated by analysis/session_a_tables.py — do not edit)', '',
         f"Protocol `{ver['protocol_sha256'][:16]}…`, result `{ver['result_sha256'][:16]}…`, "
         f"status **{ver['result_status']}**, device {res.get('device', {}).get('name')}, "
         f"driver {res.get('device', {}).get('driver_version')}.", '',
         *[f"**{k}: `{v}`**  " for k, v in d.items() if k.endswith('_decision')], '',
         '## S1. Fixed-work FP64 PCG (identical iterations and matvec calls; paired rounds)', '',
         '| case | baseline | rounds | baseline median s | modal8 median s | median ratio | one-sided 95% lower | identical work |',
         '|---|---|---:|---:|---:|---:|---:|---|']
    for e in d['fixed_work']:
        L.append(f"| {e['case']} | `{e['baseline']}` | {e['rounds']} | {e['baseline_median_seconds']:.4f} | "
                 f"{e['candidate_median_seconds']:.4f} | {e['median_ratio']:.4f} | {e['lower95']:.4f} | {e['identical_work']} |")
    L += ['', '## S2. Time to a true relative residual of 1e-8 (FP64 PCG vs donor mixed-precision refinement)', '',
          '| case | method | reps | median s | all physically passed |', '|---|---|---:|---:|---|']
    for e in d['to_tolerance']:
        L.append(f"| {e['case']} | {e['method']} | {e['repetitions']} | {e['median_seconds']:.4f} | {e['all_physical_passed']} |")
    L += ['', '## S3. Complete constrained product, per call (11 paired rounds x 20 products)', '',
          '| case | precision | baseline | baseline ms | candidate ms | median ratio | 95% lower | fastest baseline |',
          '|---|---|---|---:|---:|---:|---:|---|']
    for e in d['products']:
        L.append(f"| {e['case']} | {e['precision']} | `{e['baseline']}` | {e['baseline_median_ms']:.4f} | "
                 f"{e['candidate_median_ms']:.4f} | {e['median_ratio']:.4f} | {e['lower95']:.4f} | {e['fastest_baseline']} |")
    L += ['', '## S4. Charged setup per path (construction, compilation, material, diagonal, one capped iteration)', '',
          '| case | path | setup s |', '|---|---|---:|']
    for s in res['setups']:
        L.append(f"| {s['case']} | {s['path']} | {s['setup_seconds']:.4f} |")
    L += ['', '## S5. Product accuracy vs FP64 CPU reference (free DOFs)', '',
          '| case | path | relative L2 | limit | passed |', '|---|---|---:|---:|---|']
    for c in res['product_checks']:
        L.append(f"| {c['case']} | {c['path']} | {c['relative_l2']:.2e} | {c['limit']:.0e} | {c['passed']} |")
    tel = [t.get('output', t.get('error')) for t in res.get('telemetry', [])]
    L += ['', '## S6. Telemetry (nvidia-smi)', ''] + [f'- `{t}`' for t in tel]
    (V / f'paper/{tag}_tables.md').write_text('\n'.join(L) + '\n')
    (V / f'paper/{tag}_numbers.json').write_text(json.dumps({'decision': d, 'setups': res['setups'],
        'product_checks': res['product_checks'], 'telemetry': res.get('telemetry', []),
        'device': res.get('device')}, indent=1))
    print('\n'.join(L))


if __name__ == '__main__':
    main()
