"""Session D (multigrid) tables from the independent local verification. No hand-typed numbers.
    python3 analysis/session_d_tables.py results/session-d-20260923"""
import json, sys
from pathlib import Path
V = Path(__file__).resolve().parents[1]
run = Path(sys.argv[1]).resolve()
ver = json.loads((run / 'local-verification.json').read_text()); d = ver['decision']
res = json.loads((run / 'remote/run-01/result.json').read_text())
L = ['# session_d tables (generated by analysis/session_d_tables.py — do not edit)', '',
     f"Protocol `{ver['protocol_sha256'][:16]}…`, result `{ver['result_sha256'][:16]}…`, status **{ver['result_status']}**, "
     f"device {res['device']['name']}; evidence_valid **{ver['evidence_valid']}**.", '',
     f"**H6: `{d['h6_decision']}`** (per case {d['h6_passed']}).  ", f"**Fastest route uses modal8:** {d['h7_fastest_uses_modal8']}.", '',
     '## D1. Time to a 1e-8 true residual (median of 5; all arms identical iteration counts)', '',
     '| case | arm | median s | iterations | all passed |', '|---|---|---:|---|---|']
L += [f"| {e['case']} | {e['arm']} | {e['median_seconds']:.4f} | {e['iterations']} | {e['all_physical_passed']} |" for e in d['to_tolerance']]
L += ['', '## D2. Fixed work: arm / mg64-modal8 (10 paired rounds, identical outer iterations)', '',
      '| case | arm | median ratio | one-sided 95% lower | identical work |', '|---|---|---:|---:|---|']
L += [f"| {e['case']} | {e['numerator']} | {e['median_ratio']:.4f} | {e['lower95']:.4f} | {e['identical_work']} |" for e in d['fixed_work']]
L += ['', '## D3. Outer FP64 kernel effect under an FP32 V-cycle (best non-modal8 mixed arm / mg32-modal8-node32)', '',
      '| case | best non-modal8 mixed arm | median ratio | lower |', '|---|---|---:|---:|']
L += [f"| {c} | {e['best_non_modal8_mixed']} | {e['median_ratio']:.4f} | {e['lower95']:.4f} |" for c, e in d['outer_effect'].items()]
L += ['', '## D4. Finest-product share of one fixed-work solve (CUDA events)', '',
      '| case | arm | solve s | V-cycle finest products | outer FP64 products |', '|---|---|---:|---:|---:|']
L += [f"| {p['case']} | {p['arm']} | {p['solver_seconds']:.4f} | {p['vcycle_finest_product_seconds']/p['solver_seconds']:.1%} | {p['outer_product_seconds']/p['solver_seconds']:.1%} |" for p in d['profiles']]
L += ['', '## D5. Hierarchy and shared setup', '', '| case | levels | omegas | shared setup s |', '|---|---|---|---:|']
L += [f"| {c['case']} | {c['shapes']} | {[round(w, 3) for w in c['omegas']]} | {c['shared_setup_seconds']:.2f} |" for c in res['cases']]
(V / 'paper/session_d_tables.md').write_text('\n'.join(L) + '\n'); print('written', len(L), 'lines')
