"""Regenerate achieved residual/energy bounds from retained records (no GPU execution)."""
import json
import hashlib
import math
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper/supplement"


def scientific(value):
    mantissa, exponent = f"{value:.2e}".split("e")
    return rf"{float(mantissa):g}\times10^{{{int(exponent)}}}"


def main():
    rows = []
    groups = {
        "Session E, two RTX 4090 hosts": "results/session-e-*/remote/run-01/result.json",
        "Session I, RTX 4090": "results/session-i-rtx*/remote/run-01/result.json",
        "Session I, A100 and H100": "results/session-i-[ah]100*/remote/run-01/result.json",
    }
    for name, pattern in groups.items():
        paths = sorted(ROOT.glob(pattern))
        records = []
        limits = set()
        host_checks = []
        for path in paths:
            result = json.loads(path.read_text())
            protocol_path = path.parent / "source/protocol.json"
            protocol = json.loads(protocol_path.read_text())
            solver = protocol["solver"]
            limits.add((solver["requested_rtol"], solver["true_residual_limit"], solver["energy_force_relative_limit"]))
            samples = result["to_tolerance"]
            assert result["status"] == "completed" and samples
            assert all(all(k in r for k in ("independent_true_residual", "energy_force_relative_error", "physical_passed", "native_converged")) for r in samples)
            identities = [(r["case"], r["arm"], r["rep"]) for r in samples]
            assert len(set(identities)) == len(identities), path
            pairs = Counter((r["case"], r["arm"]) for r in samples)
            assert all(n == protocol["to_tolerance"]["repetitions"] for n in pairs.values()), path
            for case in {r["case"] for r in samples}:
                assert {r["arm"] for r in samples if r["case"] == case} == {r["id"] for r in protocol["arms"]}
            assert all(r["native_converged"] and r["native_true_residual"] <= solver["requested_rtol"] for r in samples)
            assert all(math.isfinite(r["independent_true_residual"]) and r["independent_true_residual"] <= solver["true_residual_limit"] for r in samples)
            assert all(math.isfinite(r["energy_force_relative_error"]) and r["energy_force_relative_error"] <= solver["energy_force_relative_limit"] for r in samples)
            host_checks.append({"source": str(path.relative_to(ROOT)), "protocol": str(protocol_path.relative_to(ROOT)),
                                "observations": len(samples), "cases": sorted({r["case"] for r in samples}),
                                "independent_check_stage": "CPU/C-reference check during the retained GPU run"})
            records.extend(samples)
        assert paths and records
        assert len(limits) == 1
        requested, independent_limit, energy_limit = limits.pop()
        assert all(r["physical_passed"] for r in records)
        row = dict(experiment=name, observations=len(records), requested=requested,
                   replay_limit=independent_limit, energy_limit=energy_limit,
                   observed_residual_max=max(r["independent_true_residual"] for r in records),
                   observed_native_residual_max=max(r["native_true_residual"] for r in records),
                   observed_energy_max=max(r["energy_force_relative_error"] for r in records),
                   sources=[str(p.relative_to(ROOT)) for p in paths], host_checks=host_checks)
        rows.append(row)
    saved_replays = []
    for path in sorted(ROOT.glob("results/session-e-host*/local-verification.json")):
        replay = json.loads(path.read_text())
        source = path.parent / "remote/run-01/result.json"
        assert replay["evidence_valid"] and not replay["replay_mismatches"]
        assert replay["result_sha256"] == hashlib.sha256(source.read_bytes()).hexdigest()
        assert all(r["physical_passed"] for r in replay["replays"])
        saved_replays.append({"source": str(path.relative_to(ROOT)), "observations": len(replay["replays"]),
                              "observed_residual_max": max(r["independent_true_residual"] for r in replay["replays"]),
                              "coverage": "rep=0 for every case and arm; separate retained local CPU replay"})
    out = {"scope": "retained independent-check records, not fresh replay or GPU execution", "rows": rows,
           "separate_saved_state_replays": saved_replays,
           "limits_source": "each run's archived protocol.json; replay_limit is the independent acceptance threshold, not an observed error"}
    OUT.mkdir(exist_ok=True)
    (OUT / "accuracy.json").write_text(json.dumps(out, indent=2) + "\n")
    md = ["# Retained accuracy results", "", "Generated by `python analysis/supplement_accuracy.py`. This inspects retained independent-check records; it is not a new GPU experiment or fresh state replay.", "",
          "| Experiment | In-run checked states | Requested | Independent acceptance | Observed residual maximum | Energy–work maximum (limit 1e-6) |",
          "|---|---:|---:|---:|---:|---:|"]
    for r in rows:
        md.append(f"| {r['experiment']} | {r['observations']} | {r['requested']:.0e} | {r['replay_limit']:.0e} | {r['observed_residual_max']:.8e} | {r['observed_energy_max']:.8e} |")
    md += ["", "Source records:", ""] + [f"- `{p}`" for r in rows for p in r["sources"]]
    md += ["", "Separate retained local CPU replay of saved Session E states (first repetition only):", ""]
    md += [f"- `{r['source']}`: {r['observations']} states, maximum residual {r['observed_residual_max']:.8e}; all passed." for r in saved_replays]
    md += ["", "Session I records CPU/C-reference checks during each GPU run and solution hashes; this summary does not claim a separate saved-state replay for that family."]
    (OUT / "accuracy.md").write_text("\n".join(md) + "\n")
    tex = ["% Generated by analysis/supplement_accuracy.py", r"\begin{tabular}{@{}lrrrr@{}}", r"\toprule", r"Experiment & States & Requested & Acceptance & Maximum residual \\", r"\midrule"]
    for r in rows:
        tex.append(f"{r['experiment']} & {r['observations']} & ${scientific(r['requested'])}$ & ${scientific(r['replay_limit'])}$ & ${scientific(r['observed_residual_max'])}$ " + r"\\")
    tex += [r"\bottomrule", r"\end{tabular}"]
    (OUT / "accuracy.tex").write_text("\n".join(tex) + "\n")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
